### ISSUE TITLE
Integration into emuR?

### ISSUE THREAD

**Issue by PeterGilles** [b05102139/acoustic_distance#1]
This looks interesting indeed. Would it somehow be possible to integrate this distance calculation into emuR? Phonetic segments are represented here in a SQLite database (time codes etc.) and the sound files of the larger chunks (sentences, words etc.) remain as files outside of R and the database. 

Thanks!

**Comment by soheunshim** [comment]
Hi,

In general this should be possible: an R version of the code here can also be found in the dialectR package (which is the acoustic_distance function), that should be able to be used with emuR more easily. The function currently only accepts WAV files as input however, so that may be one point to consider when trying to make the integration.
